name: flutter_app
description: A carppoling app where you can find and search for rides

version: 0.5.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:

 # datetime_picker_formfield: ^1.0.0
  #google_maps_flutter: ^0.5.26+4
  #geolocator: ^5.0.0
  #search_map_place: ^0.3.0
  #flutter_polyline_points: ^0.1.0
  #google_fonts: ^1.0.0
 # firebase_core: ^0.4.4+3
  #firebase_auth: ^0.16.0
 # cloud_firestore: ^0.13.5
 # flutter_spinkit: ^4.1.2+1
 # geoflutterfire: ^2.1.0
 # geocoder: ^0.2.1
  #fluttertoast: ^4.0.0

 # flutter_rating_bar: ^3.0.1+1
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  google_sign_in: ^6.1.0
  path: ^1.8.0
  image_picker: ^0.8.4
  sign_button: ^2.0.3
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  search_map_place_updated: ^0.0.4
  flutter_spinkit: ^5.1.0
  geocoder2: ^1.4.0
  toast: ^0.3.0
  geoflutterfire2: ^2.3.14
  datetime_picker_formfield_new: ^2.0.0
  flutter_rating_bar: ^4.0.1
  permission_handler: ^10.2.0
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^11.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/login_icon.png"


flutter:


  uses-material-design: true


  assets:
    - assets/images/login_icon.png
    - assets/map_style.txt
    - assets/images/check_img.png


  fonts:
    - family: special
      fonts:
        - asset: assets/SpecialElite-Regular.ttf

    - family: oswald
      fonts:
        - asset: assets/Oswald-Regular.ttf

    - family: pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf

    - family: fira
      fonts:
        - asset: assets/FiraSansExtraCondensed-Regular.ttf
        - asset: assets/FiraSansExtraCondensed-Light.ttf
          weight: 200
        - asset: assets/FiraSansExtraCondensed-SemiBold.ttf
          weight: 600